[project]
name = "picogpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.2",
    "numpy>=2.4.1",
    "torch>=2.9.1",
    "transformers>=4.57.5",
]
